### ISSUE TITLE
H22

### ISSUE THREAD

**Issue by Sekilsgs2** [zhangdelai-dev/work#1]
Hi.
Maybe you have H22 Amage tool and some datasheet about tuning IQ for H22?

**Comment by zhangdelai-dev** [comment]
sorry ,i don't have . you can get tools and h22 datasheet for ambrella.



软件部-张得来
深圳市金豪泰科技有限公司
深圳市宝安区71区留仙二路19号荣信兴创意园B栋303室
Tel: 0755-23016637-602
Mobile: 15814644979
Email: ***@***.*** 

 
From: Sekilsgs2
Date: 2022-04-26 13:30
To: zhangdelai-dev/work
CC: Subscribed
Subject: [zhangdelai-dev/work] H22 (Issue #1)
Hi.
Maybe you have H22 Amage tool and some datasheet about tuning IQ for H22?
